
  
Parameters:
  <<: !Include '../organization-parameters.yml'

CloudTrail:
  Type: update-stacks
  Template: ./cloud-trail.yml
  StackName: !Sub '${resourcePrefix}-cloudtrail'
  StackDescription: CloudTrail
  DefaultOrganizationBindingRegion: !Ref primaryRegion
  DefaultOrganizationBinding:
    Account: '*'
    IncludeMasterAccount: true
  OrganizationBindings:
    LogArchiveBinding:
      Account: !Ref SharedAccount #Store them in the shared account
  TerminationProtection: true
  Parameters:
    bucketName: !Sub '${resourcePrefix}-cloudtrail-${CurrentAccount.AccountId}'