Parameters:
  <<: !Include '../organization-parameters.yml'

  appName:
    Type: String
    Default: 'sso'

  # AWS SSO instance ARN
  instanceArn:
    Type: String
    Default: arn:aws:sso:::instance/ssoins-6804a00d33f24acf

  # Principal ID from Identity Provider's group used by administrators
  adminGroup:
    Type: String
    Default: 9367766dbd-0d989134-7f79-4cae-b71c-02bcd118b16a

  # Principal ID from Identity Provider's group used by developers
  developerGroup:
    Type: String
    Default: 9367766dbd-e49a6454-f15e-49b0-a368-e9e5d7aac45d

SsoAdministrator:
  Type: update-stacks
  Template: ./aws-sso.yml
  StackName: !Sub '${resourcePrefix}-${appName}-admin'
  StackDescription: 'Full permission role used by Admin group within whole organization'
  TerminationProtection: false
  DefaultOrganizationBindingRegion: !Ref primaryRegion
  DefaultOrganizationBinding:
    IncludeMasterAccount: true
  OrganizationBindings:
    TargetBinding:
      Account: '*'
  Parameters:
    instanceArn: !Ref instanceArn
    principalId: !Ref adminGroup
    permissionSetName: 'Administrator'
    managedPolicies: [ 'arn:aws:iam::aws:policy/AdministratorAccess' ]
    sessionDuration: 'PT1H'
    masterAccountId: !Ref MasterAccount

SsoDeveloper:
  Type: update-stacks
  Template: ./aws-sso.yml
  StackName: !Sub '${resourcePrefix}-${appName}-developer'
  StackDescription: 'Read and Write role used by Developer group'
  TerminationProtection: false
  DefaultOrganizationBindingRegion: !Ref primaryRegion
  DefaultOrganizationBinding:
    IncludeMasterAccount: true
  OrganizationBindings:
    TargetBinding:
      OrganizationalUnit:
        - !Ref DevelopmentOU
        - !Ref SharedOU
  Parameters:
    instanceArn: !Ref instanceArn
    principalId: !Ref developerGroup
    permissionSetName: 'Developer'
    managedPolicies: [ 'arn:aws:iam::aws:policy/PowerUserAccess' ]
    sessionDuration: 'PT12H'