name: infra.branch.push

on:
  push:
    #Both branches/branches-ignore and paths will only run when both filters are satisfied.
    branches-ignore:    
      # Push event on feature branch only
      - main
    # Path filters are not evaluated for pushes of tags
    paths:
      - infra/eks-cluster/**

permissions:
  id-token: write # required to use OIDC authentication
  contents: read  # required to checkout the code from the repo

env:
  ENV_NAME: dev
  AWS_REGION: eu-west-1
  ROOT_PATH: infra/eks-cluster

jobs:
  K8s-Cluster-Update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.ROOT_PATH }}

    steps:
      - name: Git Checkout source code
        uses: actions/checkout@v2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEV_ROLE_ARN_TF_GH_ACTIONS }}
          role-duration-seconds: 900 # the ttl of the session, in seconds.
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Update k8s Cluster RBAC roles 
        uses: kodermax/kubectl-aws-eks@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.AWS_DEV_KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "v1.23"
        with:
          args: apply -f cluster-rbac-roles.yml